version: '3.9'

services:
  python-app:
    build: .
    container_name: jup-db-basics
    depends_on:
      - mariadb
    ports:
      - "8888:8888"
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=new_backend_desarrollo
    networks:
      - my_network
    volumes:
      - "C:/Users/Usuario/Documents/triaje-db-basics:/app/shared_data"

  mariadb:
    image: mariadb:latest
    container_name: mariadb_basics
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: new_backend_desarrollo
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
